SHORT_URL_DEFAULT_LENGHT = 6
SHORT_URL_MIN_LENGHT = 2
SHORT_URL_MAX_LENGHT = 16
ORIGINAL_URL_MIN_LENGHT = 14
ORIGINAL_URL_MAX_LENGHT = 256
PATTERN_URL = r'^[a-z]+://[^\/\?:]+(:[0-9]+)?(\/.*?)?(\?.*)?$'
PATTERN_SHORT_URL = r'^[A-Za-z0-9_]{1,16}$'
